### ISSUE TITLE
Error in /db/delete_user

### ISSUE THREAD

**Issue by Filco306** [pumpumba/Influsion-back-end#109]
I get the following error printed out in the console when I try to delete a user. Deleting the user still works, but I think it would be nice to sort this error out. 

Error is found below

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
docker-node-machine |     at ServerResponse.setHeader (_http_outgoing.js:470:11)
docker-node-machine |     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:767:10)
docker-node-machine |     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
docker-node-machine |     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
docker-node-machine |     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:158:21)
docker-node-machine |     at Query.client.query [as callback] (/usr/src/app/src/index.js:454:17)
docker-node-machine |     at Query.handleReadyForQuery (/usr/src/app/node_modules/pg/lib/query.js:125:10)
docker-node-machine |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:192:19)
docker-node-machine |     at Connection.emit (events.js:182:13)
docker-node-machine |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:124:12)
```

**Comment by Ludaestro** [comment]
I can delete the user with userid 1 but I can't manage to delete a user after having it registered.
